// Telemetry event iconography (spec/22): the glyph lookup tables (by type, then
// action, then category) and the EventIcon that resolves an event to its glyph.
// A pure presentational mapping, split out of the dashboard page so page.tsx is
// the dashboard rather than also a ~110-line icon registry.
import { type ReactElement } from 'react';
import {
  ActivityGlyph,
  AlignGlyph,
  ArrowGlyph,
  BrushGlyph,
  CanvasGlyph,
  CheckGlyph,
  CircleGlyph,
  ClearGlyph,
  ClipboardGlyph,
  CloseGlyph,
  CloudGlyph,
  CommentGlyph,
  CopyGlyph,
  CylinderGlyph,
  DiagramGlyph,
  DiamondGlyph,
  DotGlyph,
  DownloadGlyph,
  ElementGlyph,
  EyeGlyph,
  FileGlyph,
  FitGlyph,
  FolderGlyph,
  GearGlyph,
  GroupGlyph,
  HeartGlyph,
  ImageGlyph,
  KeyboardGlyph,
  LayersGlyph,
  LinkGlyph,
  LockGlyph,
  MagnifierGlyph,
  MoonGlyph,
  MoveGlyph,
  NoteGlyph,
  OpenGlyph,
  PaletteGlyph,
  PencilGlyph,
  PersonAddGlyph,
  PersonGlyph,
  PlusGlyph,
  PointerGlyph,
  PolyGlyph,
  RectGlyph,
  RedoGlyph,
  ResetGlyph,
  RevertGlyph,
  ShareGlyph,
  SignInGlyph,
  SignOutGlyph,
  SparkGlyph,
  StarGlyph,
  StickyGlyph,
  SunGlyph,
  TabGlyph,
  TemplateGlyph,
  TextGlyph,
  ToggleGlyph,
  TrashGlyph,
  TriangleGlyph,
  UndoGlyph,
  UnlockGlyph,
  UploadGlyph,
  WindowGlyph,
  ZoomInGlyph,
  ZoomOutGlyph,
} from './glyphs';

// Glyph lookup for an event icon, in priority order: a type-specific glyph
// (shape kinds + other recognisable types), else an action-specific one, else
// a category fallback, else a neutral dot. Tables rather than an if-ladder so
// adding an event is a one-line entry and shared glyphs read at a glance.
const TYPE_GLYPH: Record<string, () => ReactElement> = {
  Square: RectGlyph,
  Rectangle: RectGlyph,
  Circle: CircleGlyph,
  Ellipse: CircleGlyph,
  Triangle: TriangleGlyph,
  Diamond: DiamondGlyph,
  Star: StarGlyph,
  Hexagon: PolyGlyph,
  Pentagon: PolyGlyph,
  Octagon: PolyGlyph,
  Heart: HeartGlyph,
  Cloud: CloudGlyph,
  Cylinder: CylinderGlyph,
  Arrow: ArrowGlyph,
  Text: TextGlyph,
  Sticky: StickyGlyph,
  Image: ImageGlyph,
  Dark: MoonGlyph,
  Light: SunGlyph,
  Settings: GearGlyph,
  Shortcuts: KeyboardGlyph,
  Tips: SparkGlyph,
  Share: ShareGlyph,
  Activity: ActivityGlyph,
  Welcome: SparkGlyph,
  ShareLink: LinkGlyph,
  In: ZoomInGlyph,
  Out: ZoomOutGlyph,
  Fit: FitGlyph,
  Reset: ResetGlyph,
  Edit: PencilGlyph,
  View: EyeGlyph,
  JSON: FileGlyph,
  Markdown: FileGlyph,
  PDF: FileGlyph,
  PNG: FileGlyph,
  Front: LayersGlyph,
  Back: LayersGlyph,
  FormatPainter: BrushGlyph,
  Diagram: DiagramGlyph,
  Folder: FolderGlyph,
  Tab: TabGlyph,
  Element: ElementGlyph,
};
const ACTION_GLYPH: Record<string, () => ReactElement> = {
  Deleted: TrashGlyph,
  Created: PlusGlyph,
  Added: PlusGlyph,
  Duplicated: CopyGlyph,
  Locked: LockGlyph,
  Unlocked: UnlockGlyph,
  Renamed: PencilGlyph,
  Undone: UndoGlyph,
  Redone: RedoGlyph,
  Grouped: GroupGlyph,
  Ungrouped: GroupGlyph,
  Moved: MoveGlyph,
  Reverted: RevertGlyph,
  Reordered: LayersGlyph,
  Aligned: AlignGlyph,
  Cleared: ClearGlyph,
  Linked: LinkGlyph,
  Unlinked: LinkGlyph,
  Resolved: CheckGlyph,
  Unresolved: CheckGlyph,
  Searched: MagnifierGlyph,
  Selected: PointerGlyph,
  Opened: OpenGlyph,
  Closed: CloseGlyph,
  Copied: ClipboardGlyph,
  Imported: DownloadGlyph,
  Exported: UploadGlyph,
  Shared: ShareGlyph,
  Joined: PersonGlyph,
  Used: SparkGlyph,
  Changed: PencilGlyph,
  Toggled: ToggleGlyph,
  Zoomed: FitGlyph,
  SignedIn: SignInGlyph,
  SignedUp: PersonAddGlyph,
  SignedOut: SignOutGlyph,
};
const CATEGORY_GLYPH: Record<string, () => ReactElement> = {
  Diagram: DiagramGlyph,
  Element: ElementGlyph,
  Tab: TabGlyph,
  Theme: PaletteGlyph,
  Canvas: CanvasGlyph,
  Template: TemplateGlyph,
  Comment: CommentGlyph,
  Note: NoteGlyph,
  Search: MagnifierGlyph,
  UI: WindowGlyph,
  Folder: FolderGlyph,
  Session: PersonGlyph,
  Participant: PersonGlyph,
};

export function EventIcon({
  category,
  action,
  type,
}: {
  category: string;
  action: string;
  type: string | null;
}) {
  const Glyph =
    TYPE_GLYPH[type ?? ''] ?? ACTION_GLYPH[action] ?? CATEGORY_GLYPH[category] ?? DotGlyph;
  return <Glyph />;
}
