import type { Article } from './articles';

// Help-article registry, part 3 of 4 (spec/55). articles.ts concatenates
// the four parts into the canonical browse/search order.
export const ARTICLES_PART_3: Article[] = [
  {
    slug: 'minimal-panels',
    title: 'Minimal Panels',
    description: 'Swap floating panels for a compact button bar.',
    category: 'Palette',
    categorySlug: 'palette',
    group: 'Palette Settings',
  },
  {
    slug: 'reset-palette-position',
    title: 'Reset Palette Position',
    description: 'Snap the palette back to its default corner.',
    category: 'Palette',
    categorySlug: 'palette',
    group: 'Palette Settings',
  },
  {
    slug: 'selecting-and-grouping',
    title: 'Selecting and Grouping',
    description: 'Marquee, multi-select, groups, and the format painter.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'text-and-fonts',
    title: 'Text and Fonts',
    description: 'Editing labels and choosing from eight fonts per element or tab.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'themes',
    title: 'Themes',
    description: 'Restyle a whole diagram, including multi-colour and custom themes.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'templates',
    title: 'Templates',
    description: 'Start from a themed template instead of a blank canvas.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'using-tabs',
    title: 'Tabs',
    description: 'Multiple boards in one diagram: add, name, reorder, and switch between them.',
    category: 'Tabs',
    categorySlug: 'tabs',
  },
  {
    slug: 'tab-folders',
    title: 'Tab Folders',
    description: 'Group related tabs under a named, collapsible folder along the tab bar.',
    category: 'Tabs',
    categorySlug: 'tabs',
  },
  {
    slug: 'linking-tabs',
    title: 'Linking Across Tabs',
    description: 'Turn an element into a jump point to another tab, element, diagram, or URL.',
    category: 'Tabs',
    categorySlug: 'tabs',
  },
  {
    slug: 'locking-tabs',
    title: 'Locking a Tab',
    description: 'Make a whole board read-only so it cannot be changed by accident.',
    category: 'Tabs',
    categorySlug: 'tabs',
  },
  {
    slug: 'add-to-diagram',
    title: 'Add a Tab to Another Diagram',
    description: 'Copy the active tab into another diagram you own from the tab menu.',
    category: 'Tabs',
    categorySlug: 'tabs',
  },
  {
    slug: 'import-tabs',
    title: 'Importing a Tab',
    description: 'Import a JSON or Markdown file into the active tab (it replaces the contents).',
    category: 'Tabs',
    categorySlug: 'tabs',
  },
  {
    slug: 'export-tabs',
    title: 'Exporting a Tab',
    description: 'Export the active tab as PNG, SVG, PDF, Markdown, or a livediagram JSON file.',
    category: 'Tabs',
    categorySlug: 'tabs',
  },
  {
    slug: 'tab-cleanup',
    title: 'Cleaning Up a Tab',
    description: 'Tidy a tab in one click: snap to a grid, or auto-lay-out from the arrows.',
    category: 'Tabs',
    categorySlug: 'tabs',
  },
  {
    slug: 'comments',
    title: 'Comments',
    description: 'Leave threaded comments on the canvas and resolve them.',
    category: 'Collaboration',
    categorySlug: 'collaboration',
  },
  {
    slug: 'live-presence',
    title: 'Live Presence',
    description: 'Live cursors, names, selections, and who is on which tab, in real time.',
    category: 'Collaboration',
    categorySlug: 'collaboration',
  },
  {
    slug: 'links',
    title: 'Links and Link Cards',
    description: 'Link elements across tabs or to URLs, and bookmark cards.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'explorer-page',
    title: 'Explorer Page',
    description: 'The full-page library: the sidebar sections, list view, and folders.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'explorer-panel',
    title: 'Explorer Panel',
    description:
      'The compact in-editor Explorer for switching diagrams without leaving the canvas.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'recent',
    title: 'Recent Diagrams',
    description: 'The default view: the diagrams you opened or edited most recently.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'shared-with-you',
    title: 'Shared With You',
    description: 'Diagrams other people have shared with you, collected in one place.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'folders',
    title: 'Folders',
    description: 'Group diagrams into a nestable tree, and move them between folders.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'unsorted',
    title: 'The Unsorted Folder',
    description: 'The catch-all for diagrams that are not filed in any folder yet.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'my-work',
    title: 'My Work and Folders',
    description: 'Your own library: the Unsorted bucket and the nested folders you create.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'team-spaces',
    title: 'Team Spaces',
    description: 'The teams you belong to, their shared folders, and your pending invites.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'image-gallery',
    title: 'Image Gallery',
    description: 'Every image you have uploaded, with where each is used and how to delete them.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'themes-library',
    title: 'Saved Themes',
    description: 'Your custom themes as swatch previews, ready to edit, duplicate, or reuse.',
    category: 'Explorer',
    categorySlug: 'explorer',
  },
  {
    slug: 'teams',
    title: 'Teams',
    description: 'Invite members, assign roles, and share diagrams across a team.',
    category: 'Collaboration',
    categorySlug: 'collaboration',
  },
  {
    slug: 'sharing',
    title: 'Sharing and Embeds',
    description: 'Share links, passwords, expiry, read-only embeds, and live images.',
    category: 'Collaboration',
    categorySlug: 'collaboration',
  },
  {
    slug: 'zen-mode',
    title: 'Zen Mode',
    description: 'A distraction-free canvas with all the chrome hidden.',
    category: 'Tools',
    categorySlug: 'tools',
  },
  {
    slug: 'dark-mode',
    title: 'Light and Dark Mode',
    description: 'Flip the editor chrome between light and dark, separate from your diagram theme.',
    category: 'Tools',
    categorySlug: 'tools',
  },
  {
    slug: 'ai',
    title: 'AI Assistance',
    description: 'Optional Ask and Clean helpers on the canvas.',
    category: 'Tools',
    categorySlug: 'tools',
  },
  {
    slug: 'markdown-import',
    title: 'Markdown Import',
    description: 'Turn a Markdown outline into a themed tree diagram.',
    category: 'Tools',
    categorySlug: 'tools',
  },
  {
    slug: 'session-tools',
    title: 'Session Tools',
    description: 'A shared countdown or stopwatch and live dot-voting.',
    category: 'Collaboration',
    categorySlug: 'collaboration',
  },
  {
    slug: 'style-presets',
    title: 'Style Presets',
    description: 'One-click colour and line-style variations for shapes and arrows.',
    category: 'Palette',
    categorySlug: 'palette/shapes',
    parentSlug: 'shapes',
  },
  {
    slug: 'layout-cleanup',
    title: 'Layout Cleanup',
    description: 'Auto-align to a grid or auto-layout the whole diagram.',
    category: 'Tools',
    categorySlug: 'tools',
  },
  {
    slug: 'annotations',
    title: 'Annotations',
    description: 'Drop a marker with a note that readers hover to read.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'layer-order',
    title: 'Layer Order and Opacity',
    description: 'Bring elements to front or back, and fade them with opacity.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'rotation',
    title: 'Rotating Elements',
    description:
      'Snap an element to a preset 45° angle from the right-click menu or search palette.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'animations',
    title: 'Animating Elements',
    description: 'Loop a subtle animation on shapes, arrows, and icons.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'locking',
    title: 'Locking Elements',
    description: 'Protect an element from accidental moves, resizes, and deletion.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },
  {
    slug: 'snapping',
    title: 'Alignment & Snapping',
    description: 'Drag to snap elements into line with guides; hold Cmd/Ctrl to place freely.',
    category: 'Canvas',
    categorySlug: 'canvas',
  },

  // ---- Sub-articles: Canvas ----
  {
    slug: 'adding-elements',
    title: 'Adding Elements',
    description: 'Use the palette and double-click to place shapes.',
    category: 'Canvas',
    categorySlug: 'canvas/the-canvas',
    parentSlug: 'the-canvas',
  },
  {
    slug: 'pan-and-zoom',
    title: 'Panning and Zooming',
    description: 'Move around the infinite canvas and fit the view.',
    category: 'Canvas',
    categorySlug: 'canvas/the-canvas',
    parentSlug: 'the-canvas',
  },
];
